name: create a check in a steps

on:
  pull_request:

permissions:
  checks: write

jobs:
  pull_request_job:
    name: run on pull request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: step to create a check in_progress
        uses: actions/github-script@v6
        id: create-check
        with:
          result-encoding: string
          script: |
            const checkStatus = "in_progress";
            const commitSha = "${{ github.event.pull_request.head.sha }}";

            // Create the check
            const check = await github.rest.checks.create({
              owner: process.env.GITHUB_REPOSITORY.split('/')[0],
              repo: process.env.GITHUB_REPOSITORY.split('/')[1],
              name: "My first check",
              head_sha: commitSha,
              status: "in_progress",
              output: {
                title: "Check passed",
                summary: "Everything is okay",
                text: "You can put text in here"
              }
            });

            console.log(`In progress check created with ID: ${check.data.id}`);
            return check.data.id