name: Alerting on GitHub Spend

run-name: CRON - Spend Alerting Monitor (Business Hours)

on:
  schedule:
    - cron: '0,30 6-19 * * 1-5'
  workflow_dispatch:

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Source GitHub Actions billing information
        id: actions-billing
        uses: keita-hino/get-billing-for-github-actions@v1.0.0
        with:
          # For organization accounts, set the `org` parameter.
          account-type: org
          github-token: ${{ secrets.REPOSITORY_ADMIN_PAT }}
      - name: Send Billing data to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text":"The usage limit of GitHub Actions for the current plan is *${{steps.actions-billing.outputs.included-minutes}}* minutes.\nThe usage for this month is *${{steps.actions-billing.outputs.total-minutes-used}}* minutes, and there are *${{steps.actions-billing.outputs.usable-minutes}}* minutes remaining.\nThe next reset day is in *${{steps.actions-billing.outputs.days-left-in-billing-cycle}}* days.",
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "The usage limit of GitHub Actions for the current plan is *${{steps.actions-billing.outputs.included-minutes}}* minutes.\nThe usage for this month is *${{steps.actions-billing.outputs.total-minutes-used}}* minutes, and there are *${{steps.actions-billing.outputs.usable-minutes}}* minutes remaining.\nThe next reset day is in *${{steps.actions-billing.outputs.days-left-in-billing-cycle}}* days."
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.FINOPS_SLACK_CHANNEL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
